version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "sam-athena-app"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1kjqzy0abzdhz"
s3_prefix = "sam-athena-app"
region = "eu-west-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
parameter_overrides = "AthenaWorkGroupName=\"primary\" S3BucketName=\"sabsden\""
image_repositories = []
